name: mindease
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.0.0
  aws_client: ^0.4.1
  bcrypt: ^1.1.3
  calendar_date_picker2: ^1.1.5
  chewie: ^1.8.1
  facebook_auth: ^0.0.3
  firebase_auth: ^3.1.3
  firebase_core: ^1.10.6
  flutter_email_sender: ^6.0.3
  flutter_facebook_auth: ^7.0.1
  flutter_inappwebview: ^6.0.0
  flutter_markdown: ^0.6.3
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^9.2.0
  google_sign_in: ^6.2.1
  groq: ^0.0.4
  http: ^1.2.1
  image_picker: ^0.8.4+4
  just_audio: ^0.9.38
  mongo_dart: ^0.10.3
  provider: ^6.0.2
  shared_preferences: ^2.0.12
  table_calendar: ^3.0.8
  tuple: ^2.0.2
  video_player: ^2.2.12
  window_manager: ^0.3.9
  youtube_player_flutter: ^9.0.1
  youtube_player_iframe: ^5.1.3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/home.jpg
    - assets/images/mindfulness.jpg
    - assets/images/meditazione.jpg
    - assets/images/background.jpg
    - assets/images/montagna.jpg
    - assets/images/supporto.png
    - assets/images/resp.jpg
    - assets/images/listening.jpg
    - assets/images/suoni.jpeg
    - assets/images/calend.png
    - assets/images/psicologo.png
    - assets/images/mostro.png
    - assets/images/trofeo.png
    - assets/images/emotion/annoiato.png
    - assets/images/emotion/ansia.png
    - assets/images/emotion/arabbiato.png
    - assets/images/emotion/calmo.png
    - assets/images/emotion/eccitato.png
    - assets/images/emotion/felice.png
    - assets/images/emotion/preoccupato.png
    - assets/images/emotion/rilassato.png
    - assets/images/emotion/stanco.png
    - assets/images/emotion/stressed.png
    - assets/images/emotion/triste.png
    - assets/images/sintomi/headache.png
    - assets/images/sintomi/heart.png
    - assets/images/sintomi/insomnia.png
    - assets/images/sintomi/nervous.png
    - assets/images/sintomi/parkinson.png
    - assets/images/sintomi/stomackache.png
    - assets/images/user/profilo.png
    - assets/images/user/p2.png
    - assets/images/user/p3.png
    - assets/images/user/p4.png
    - assets/images/user/p5.png
    - assets/images/user/p6.png
    - assets/images/user/p7.png
    - assets/sound/Beach Waves.mp3
    - assets/sound/Beach.mp3
    - assets/sound/Bosco & Uccelli.mp3
    - assets/sound/Cinguettio rilassante.mp3
    - assets/sound/Fire Crackle At the Lake.mp3
    - assets/sound/Gentle Rivers and Streams.mp3
    - assets/sound/Hazard Beach.mp3
    - assets/sound/Mountain Rain.mp3
    - assets/sound/Musica di rilassamento con uccelli.mp3
    - assets/sound/Natural Meditation.mp3
    - assets/sound/Nature Sounds of the Ocean.mp3
    - assets/sound/Ocean Relax.mp3
    - assets/sound/Ocean Waves .mp3
    - assets/sound/Oltre le nuvole (suono rilassante di uccelli).mp3
    - assets/sound/Piccoli uccellini.mp3
    - assets/sound/Piccoli volatili.mp3
    - assets/sound/Relaxing Rain.mp3
    - assets/sound/River, Thunder & Rain - Calm Excitement.mp3
    - assets/sound/Soft Sounds of the Night.mp3
    - assets/sound/Suburban Forest Rain 2.mp3
    - assets/sound/Suoni degli uccelli.mp3
    - assets/sound/The Babbling Brook - Scotland.mp3
    - assets/sound/The Sound Of The Jungle With Coloured Birds For Relaxation, Sleeping, Studying.mp3
    - assets/sound/Thunderstorm and Rain Music.mp3
    - assets/sound/Tranquil Babbling Brook for Deep Sleep.mp3
    - assets/sound/White Noise Rain and River.mp3



  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/chinese.msyh.ttf