name: flutter_mindease
description: "A Flutter project to manage anxiety"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  window_manager: ^0.3.8
  table_calendar: ^3.0.1
  http: ^1.2.1
  font_awesome_flutter: ^9.2.0
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.12
  flutter_markdown: ^0.6.3  # Add markdown dependency
  groq: ^0.0.4  # Add groq dependency
  tuple: ^2.0.2  # Add tuple dependency
  mongo_dart: ^0.8.1
  bcrypt: ^1.1.3
  video_player: ^2.2.12
  audioplayers: ^6.0.0
  just_audio: ^0.9.38 
  firebase_auth: ^3.1.3  
  firebase_core: ^1.10.6  
  flutter_facebook_auth: ^7.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/home.jpg
    - assets/images/mindfulness.jpg
    - assets/images/meditazione.jpg
    - assets/images/background.jpg
    - assets/images/montagna.jpg
    - assets/images/supporto.png
    - assets/images/resp.jpg
    - assets/images/suoni.jpeg
    - assets/images/calend.png
    - assets/images/psicologo.png
    - assets/images/mostro.png
    - assets/images/trofeo.png
    - assets/images/emotion/annoiato.png
    - assets/images/emotion/ansia.png
    - assets/images/emotion/arabbiato.png
    - assets/images/emotion/calmo.png
    - assets/images/emotion/eccitato.png
    - assets/images/emotion/felice.png
    - assets/images/emotion/preoccupato.png
    - assets/images/emotion/rilassato.png
    - assets/images/emotion/stanco.png
    - assets/images/emotion/stressed.png
    - assets/images/emotion/triste.png
    - assets/images/sintomi/headache.png
    - assets/images/sintomi/heart.png
    - assets/images/sintomi/insomnia.png
    - assets/images/sintomi/nervous.png
    - assets/images/sintomi/parkinson.png
    - assets/images/sintomi/stomackache.png
    - assets/images/user/profilo.png
    - assets/images/user/p2.png
    - assets/images/user/p3.png
    - assets/images/user/p4.png
    - assets/images/user/p5.png
    - assets/images/user/p6.png
    - assets/images/user/p7.png
    - assets/images/user/p8.png

  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/chinese.msyh.ttf
